FROM nginx
LABEL maintainer="kugou_stock_points web Maintainers <jarvenwang@kugou.net>"
WORKDIR /var/www/html/TME_KG_STOCK_POINTS_WEB
ADD ./TME_KG_STOCK_POINTS_WEB /var/www/html/TME_KG_STOCK_POINTS_WEB
EXPOSE 80
