FROM nginx
LABEL maintainer="kugou_stock_points api_nginx Maintainers <jarvenwang@kugou.net>"
WORKDIR /var/www/html/TME_KG_STOCK_POINTS_API
ADD ./TME_KG_STOCK_POINTS_API /var/www/html/TME_KG_STOCK_POINTS_API
ADD ./.env /var/www/html/TME_KG_STOCK_POINTS_API/.env
EXPOSE 80
