FROM wurstmeister/zookeeper
# RUN echo "deb http://mirrors.163.com/debian/ bullseye main non-free contrib \n \
#     deb http://mirrors.163.com/debian/ bullseye-updates main non-free contrib \n \
#     deb http://mirrors.163.com/debian/ bullseye-backports main non-free contrib \n \
#     deb-src http://mirrors.163.com/debian/ bullseye main non-free contrib \n \
#     deb-src http://mirrors.163.com/debian/ bullseye-updates main non-free contrib \n \
#     deb-src http://mirrors.163.com/debian/ bullseye-backports main non-free contrib \n \
#     deb http://mirrors.ustc.edu.cn/debian-security/ stable-security main non-free contrib \n \
#     deb-src http://mirrors.ustc.edu.cn/debian-security/ stable-security main non-free contrib" > /etc/apt/sources.list
# RUN apt-get update && apt-get install -y vim

