# 使用官方 Node 22.19 镜像
FROM node:22.19

# FROM node:22.11.0

# # 安装 pnpm
# RUN npm install -g pnpm@10.7.0

# WORKDIR /app

# # 复制依赖文件
# COPY package.json pnpm-lock.yaml ./

# # 安装依赖
# RUN pnpm install --frozen-lockfile

# # 复制项目代码
# COPY . .

# # 构建 dist
# RUN pnpm run build-only